{{- /*
Author KYH.
blue app service
*/}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-blue-service
    app.kubernetes.io/managed-by: Helm
  name: nginx-blue-service
spec:
  ports:
  {{- if .Values.containerPorts.http }}
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort.http }}
  {{- end }}
  {{- if .Values.containerPorts.https }}
  - name: https
    port: {{ .Values.service.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort.https }}
  {{- end }}
  selector:
    app: blue
  type: null
---
{{- /*
Author KYH.
green app service
*/}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-green-service
    app.kubernetes.io/managed-by: Helm
  name: nginx-green-service
spec:
  ports:
  {{- if .Values.containerPorts.http }}
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort.http }}
  {{- end }}
  {{- if .Values.containerPorts.https }}
  - name: https
    port: {{ .Values.service.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort.https }}
  {{- end }}
  selector:
    app: green
  type: null
