{{- /*
Author KYH.
nginx pvc
*/}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: nginx-pvc
  namespace: study-helm
spec:
  storageClassName: openebs-hostpath
  accessModes: {{- toYaml .Values.pvc.accessModes | nindent 2 }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  resources: {{- toYaml .Values.pvc.resources | nindent 4 }}