{{- /*
Author KYH.
nginx pod reader rolebinding
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podreader-rolebinding
  namespace: study-helm
roleRef: {{- toYaml .Values.rolebinding.roleRef | nindent 2 }}
subjects: {{- toYaml .Values.rolebinding.subjects | nindent 2 }}