{{- /*
Author KYH.
nginx pod reader rolebinding
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podreader-rolebinding
  namespace: study-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podreader-role
subjects:
- kind: ServiceAccount
  name: nginx-sa
  namespace: study-helm