{{- /*
Author KYH.
blue app traefik ingress route CRD
*/}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-blue-ingressroute
  namespace: study-helm
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`blue.myweb.com`)
    kind: Rule
    services:
    - name: nginx-blue-service
    {{- if .Values.containerPorts.http }}
      port: {{ .Values.service.ports.http }}
    {{- end }}
    {{- if .Values.containerPorts.https }}
      port: {{ .Values.service.ports.https }}
    {{- end }}
---
{{- /*
Author KYH.
green app traefik ingress route CRD
*/}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-green-ingressroute
  namespace: study-helm
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`green.myweb.com`)
    kind: Rule
    services:
    - name: nginx-green-service
    {{- if .Values.containerPorts.http }}
      port: {{ .Values.service.ports.http }}
    {{- end }}
    {{- if .Values.containerPorts.https }}
      port: {{ .Values.service.ports.https }}
    {{- end }}