{{- /*
Author KYH.
nginx hpa for blue deployment
*/}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-blue-hpa
  namespace: study-helm
spec:
  maxReplicas: 10
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-blue-deployment
  # targetCPUUtilizationPercentage: 50 # autoscaling/v1
  metrics: {{ toYaml .Values.hpa.resource | nindent 2 }}
---
{{- /*
Author KYH.
nginx hpa for green deployment
*/}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-green-hpa
spec:
  maxReplicas: 10
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-green-deployment
  # targetCPUUtilizationPercentage: 50 # autoscaling/v1
  metrics: {{ toYaml .Values.hpa.resource | nindent 2 }}
