{{- /*
Author KYH.
blue app deployment
*/}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: nginx-blue-deployment
  name: nginx-blue-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: blue
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: blue
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.serviceAccountName }}
      {{- end }}
      containers:
      - name: hello-blue
        image: {{ include "nginx.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- .Values.resources | toYaml | nindent 10}}
        {{- if and .Values.volumeMounts .Values.volumes }}
        volumeMounts:
        - name: {{ .Values.volumeMounts.openebsHostpath.name }}
          mountPath: {{ .Values.volumeMounts.mountPath }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes: {{- .Values.volumes | toYaml | nindent 6 }}
      {{- end }}
---
{{- /*
Author KYH.
green app deployment
*/}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: nginx-green-deployment
  name: nginx-green-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: green
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: green
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.serviceAccountName }}
      {{- end }}
      containers:
      - name: hello-green
        image: {{ include "nginx.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- .Values.resources | toYaml | nindent 10}}
        {{- if and .Values.volumeMounts .Values.volumes }}
        volumeMounts:
        - name: {{ .Values.volumeMounts.emptydir.name }}
          mountPath: {{ .Values.volumeMounts.mountPath }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes: {{- .Values.volumes | toYaml | nindent 6 }}
      {{- end }}